name: 'Test Python'
author: 'EnricoMi'
description: 'A GitHub Action that tests Python spark-dgraph-connector'

inputs:
  spark-version:
    description: Spark version, e.g. 3.4.0 or 3.4.0-SNAPSHOT
    required: true
  scala-version:
    description: Scala version, e.g. 2.12.15
    required: true
  spark-compat-version:
    description: Spark compatibility version, e.g. 3.4
    required: true
  scala-compat-version:
    description: Scala compatibility version, e.g. 2.12
    required: true
  dgraph-version:
    description: Dgraph server version, e.g. 22.0.0
    required: true
  python-version:
    description: Python version, e.g. 3.8 or 3.8.0
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set versions in pom.xml
      run: |
        ./set-version.sh ${{ inputs.spark-version }} ${{ inputs.scala-version }}
        git diff
      shell: bash

    - name: Fetch Binaries Artifact
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: Binaries-${{ inputs.spark-compat-version }}-${{ inputs.scala-compat-version }}
        path: .

    - name: Fetch Dependencies Artifact
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: Dependencies-${{ inputs.spark-compat-version }}-${{ inputs.scala-compat-version }}
        path: ~/.m2/repository

    - name: Setup JDK 11
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Start Dgraph cluster
      id: dgraph
      env:
        DGRAPH_TEST_CLUSTER_VERSION: ${{ inputs.dgraph-version }}
      run: |
        cp -v dgraph-instance.*.sh /tmp/
        echo "docker=$(/tmp/dgraph-instance.background.sh)" >> $GITHUB_OUTPUT
        sleep 10
        if [[ "${{ inputs.dgraph-version }}" != "20.03."* ]]
        then
          /tmp/dgraph-instance.drop-all.sh
        fi
        /tmp/dgraph-instance.schema.sh
        /tmp/dgraph-instance.insert.sh
      shell: bash

    - name: Cache Pip packages
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-test-${{ inputs.python-version }}-${{ inputs.spark-version }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-test-${{ inputs.python-version }}-${{ inputs.spark-version }}-

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements.txt
        pip install pytest
      shell: bash

    - name: Python Test
      env:
        DGRAPH_TEST_CLUSTER_VERSION: ${{ inputs.dgraph-version }}
        PYTHONPATH: python:python/test
      run: |
        mkdir -p target/surefire-reports
        python -m pytest python/test --junit-xml target/surefire-reports/pytest.xml
      shell: bash

    - name: Upload Unit Test Results
      if: always()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: Unit Test Results (Spark ${{ inputs.spark-version }}, Scala ${{ inputs.scala-version}}, Dgraph ${{ inputs.dgraph-version }}, Python ${{ inputs.python-version }})
        path: |
          target/surefire-reports/*.xml
          !target/surefire-reports/TEST-org.scalatest*.xml
          target/site/surefire-report.html

branding:
  icon: 'check-circle'
  color: 'green'
