name: Test Integration

on:
  workflow_call:

jobs:
  test-integration:
    name: Integration Tests (Dgraph ${{ matrix.dgraph-version }} Spark ${{ matrix.spark-version }} Scala ${{ matrix.scala-compat-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        spark-compat-version: ["3.4", "3.5"]
        dgraph-minor-version: ["20.03", "20.07", "20.11", "21.12", "22.0", "23.0", "23.1", "24.0"]
        scala-compat-version: ["2.12"]
        include:
          - spark-compat-version: '3.0'
            spark-version: '3.0.3'
            scala-compat-version: '2.12'
            scala-version: '2.12.10'
            dgraph-minor-version: "22.0"
            dgraph-version: "22.0.2"
            hadoop-version: '2.7'

          - spark-compat-version: '3.1'
            spark-version: '3.1.3'
            scala-compat-version: '2.12'
            scala-version: '2.12.10'
            dgraph-minor-version: "22.0"
            dgraph-version: "22.0.2"
            hadoop-version: '2.7'

          - spark-compat-version: '3.2'
            spark-version: '3.2.4'
            scala-compat-version: '2.12'
            scala-version: '2.12.15'
            dgraph-minor-version: "22.0"
            dgraph-version: "22.0.2"
            hadoop-version: '2.7'

          - spark-compat-version: '3.3'
            spark-version: '3.3.4'
            scala-compat-version: '2.12'
            scala-version: '2.12.15'
            dgraph-minor-version: "22.0"
            dgraph-version: "22.0.2"
            hadoop-version: '3'

          - spark-compat-version: '3.4'
            spark-version: '3.4.3'
            scala-compat-version: '2.12'
            scala-version: '2.12.17'
            hadoop-version: '3'
          - spark-compat-version: '3.5'
            spark-version: '3.5.1'
            scala-compat-version: '2.12'
            scala-version: '2.12.17'
            hadoop-version: '3'

          - dgraph-minor-version: "20.03"
            dgraph-version: "20.03.7"
          - dgraph-minor-version: "20.07"
            dgraph-version: "20.07.3"
          - dgraph-minor-version: "20.11"
            dgraph-version: "20.11.3"
          - dgraph-minor-version: "21.12"
            dgraph-version: "21.12.0"
          - dgraph-minor-version: "22.0"
            dgraph-version: "22.0.2"
          - dgraph-minor-version: "23.0"
            dgraph-version: "23.0.1"
          - dgraph-minor-version: "23.1"
            dgraph-version: "23.1.1"
          - dgraph-minor-version: "24.0"
            dgraph-version: "24.0.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        uses: ./.github/actions/test-integrate
        with:
          spark-version: ${{ matrix.spark-version }}
          scala-version: ${{ matrix.scala-version }}
          spark-compat-version: ${{ matrix.spark-compat-version }}
          scala-compat-version: ${{ matrix.scala-compat-version }}
          dgraph-version: ${{ matrix.dgraph-version }}
          hadoop-version: ${{ matrix.hadoop-version }}

